### ISSUE TITLE
stack2nix cannot run on itself

### ISSUE THREAD

**Issue by nc6** [typeable/stackage2nix#16]
```
[nc@varda:~/proj/stack2nix]$ ~/.local/bin/stack2nix --all-cabal-hashes ~/proj/all-cabal-hashes/ --lts-haskell ~/proj/lts-haskell/ .
downloading ‘https://github.com/4e6/cabal2nix.git’... [28/0 KiB, 27.9 KiB/s]
*** parsing cabal file: https://github.com/4e6/cabal2nix.git: openBinaryFile: does not exist (No such file or directory)
stack2nix: nix-prefetch-git: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by 4e6** [comment]
Since stack.yaml contains GitHub (git) dependencies, `nix-prefetch-git` executable is expected to be on PATH. This is the logic of `cabal2nix`since it is responsible for producing derivations. 
For example, try to run `cabal2nix https://github.com/4e6/cabal2nix.git`

There is example where `stack2nix` builds itself in the stack2nix-examples repo ttps://github.com/4e6/stack2nix-examples/blob/master/.travis.yml#L22

**Comment by nc6** [comment]
Seems to fail in another way now:
```
[nc@varda:~/proj/stack2nix.master]$ stack exec -- stackage2nix --all-cabal-hashes $HOME/proj/all-cabal-hashes/ --lts-haskell $HOME/proj/lts-haskell/ .
stackage2nix: nix-env: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by nc6** [comment]
Interesting - this works if run directly, but not if run through `stack exec`

**Comment by 4e6** [comment]
`distribution-nixpkgs` requires `nix-env` executable on PATH. Agree, it's not that obvious. I'll update readme accordingly.

**Comment by Fuuzetsu** [comment]
You need `nix-shell -p haskellPackages.stack nix-prefetch-scripts` and to exec you should also pass `--no-nix-pure` so that nix-env and prefetch scripts stay in PATH. Another hidden requirement is likely running nix-daemon and NIX_REMOTE=daemon which is needed by nix-prefetch-git

I severely dislike this aspect of cabal2nix: if we want stackage2nix to Just Work such as when it's called from scripts, it would be wise to not let cabal2nix perform the git fetch but that we should do it ourselves and patch resulting src. Or something.
