### ISSUE TITLE
support buildHaskellPackages attribute

### ISSUE THREAD

**Issue by nmattia** [typeable/stackage2nix#52]
A (mandatory) attribute was [recently added](https://github.com/NixOS/nixpkgs/pull/26799) `make-package-set.nix` and other haskell functions (in particular this is needed when calling `haskell-modules`). Does `stackage2nix` support that? Also, the actual `stackage2nix` derivation will need to be updated: https://github.com/typeable/stackage2nix/blob/master/nix/haskell-packages/default.nix#L88

**Comment by 4e6** [comment]
This issue was discussed in https://github.com/typeable/nixpkgs-stackage/issues/12

TLDR, it takes much effort to keep up with _nixpkgs-unstable_, so _stackage2nix_ is focused on the stable release. 

- `makePackageSet` is supported. I've added dummy argument `buildHaskellPackages ? null` in https://github.com/NixOS/nixpkgs/pull/34557 and fixed code-generation in https://github.com/typeable/stackage2nix/pull/51
- `<haskell-modules/default.nix>` is not supported, because master and release versions have different argument sets. We'll add `buildHaskellPackages` argument when it merges to the stable branch.

**Comment by nmattia** [comment]
@4e6 thanks a lot, I totally missed that thread!
